Repository LinkrewProject/Linkrew-frontend, pull requests merged in 2025-05, with the labels that each got.

#63 chore: https 설정 제거
  vite.config.ts
Labels: 🧹Setting

#62 chore: 엔드포인트 baseurl,auth 및 axiosInstance 세팅
  env.d.ts
  src/apis/axiosInstance.ts
  src/components/page-layout/PageLayout.tsx
  tsconfig.app.json
Labels: 🧹Setting

#64 feat: 회원가입 페이지 select 컴포넌트 구현
  src/components/common-ui/Select.tsx
  src/pages/pages/auth/signup/index.tsx
  vite.config.ts
Labels: ✨ Feature, 🎨 HTML&CSS, 🧹Setting

#66 style: psudo class 추가 및 모달 스타일 변경
  src/components/common-ui/ContextMenu.tsx
  src/components/header/HamburgerButton.tsx
  src/components/header/UserActions.tsx
  src/components/modal/modal-page/ModalMenu.tsx
  src/components/modal/modal-page/ModalNotification.tsx
  src/components/page-layout/PageLayout.tsx
Labels: 🎨 HTML&CSS

#68 feat: 인증 상태에 따른 라우터 리다이렉트 기능 구현
  src/components/common-ui/ProtectedRoute.tsx
  src/components/common-ui/RedirectIfAuthenticated.tsx
  src/hooks/useAuth.ts
  src/routes/Router.tsx
Labels: ✨ Feature

#70 feat: jwt 인증 및 보호된 라우트 구현
  package-lock.json
  package.json
  src/hooks/useAuth.ts
  src/routes/Router.tsx
  src/routes/guards/ProtectedRoute.tsx
  src/routes/guards/RedirectIfAuthenticated.tsx
Labels: ✨ Feature, 🔄 Refactor

#71 fix: 소셜 로그인 리다이렉트 및 CORS 이슈 해결
  src/components/page-layout/PageLayout.tsx
  src/pages/pages/auth/login/index.tsx
  src/pages/pages/reissue/page.tsx
  vite.config.ts
Labels: 🔧 BugFix

#72 style: pageLayout 반응형 제작 및 모듈화
  Dockerfile
  docker-compose.local.yml
  docker-compose.yml
  src/assets/common-ui-assets/FolderItemIcon.svg
  src/assets/common-ui-assets/LinkItemIcon.svg
  src/assets/widget-ui-assets/SiteIcon.svg
  src/components/header/BreadCrumb.tsx
  src/components/header/Header.tsx
  src/components/page-layout/FolderItem.tsx
  src/components/page-layout/LinkItem.tsx
  src/components/page-layout/PageContentSection.tsx
  src/components/page-layout/PageControllerSection.tsx
  src/components/page-layout/PageHeaderSection.tsx
  src/components/page-layout/PageLayout.tsx
  src/components/side-bar/SideBar.tsx
  src/hooks/useClickOutside.ts
  src/hooks/useMobile.ts
  src/layout/layout.tsx
  src/styles/global.css
  src/types/pageItems.ts
Labels: 🎨 HTML&CSS

#74 feat: 폴더 관리 모달 컴포넌트 구현
  src/assets/common-ui-assets/Status.svg
  src/components/common-ui/Input.tsx
  src/components/common-ui/Modal.tsx
  src/components/modal/folder/AddFolderModal.tsx
  src/components/modal/folder/DeleteFolderModal.tsx
  src/components/modal/folder/ErrorModal.tsx
  src/components/modal/folder/FolderTransferModal.tsx
  src/components/page-layout/PageControllerSection.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#75 feat: 링크 관리 모달 컴포넌트 구현
  src/components/common-ui/Input.tsx
  src/components/common-ui/Textarea.tsx
  src/components/modal/link/AddLinkModal.tsx
  src/components/modal/link/DeleteLinkModal.tsx
  src/components/page-layout/PageControllerSection.tsx
Labels: ✨ Feature

#77 fix: reissue 수정 및 cors에러 확인 후 api 호출 테스트
  src/apis/axiosInstance.ts
  src/components/page-layout/PageControllerSection.tsx
  src/components/page-layout/PageLayout.tsx
  src/components/side-bar/SideBar.tsx
  src/pages/PersonalPage.tsx
  src/pages/pages/auth/signup/index.tsx
  src/pages/pages/reissue/page.tsx
  src/routes/Router.tsx
  vite.config.ts
Labels: 🔧 BugFix, ✨ Feature

#78 feat: page api 통신 및 유저정보 전역상태관리
  package-lock.json
  package.json
  src/apis/axiosInstance.ts
  src/apis/page-apis/createSharedPage.ts
  src/apis/page-apis/fetchJoinedPage.ts
  src/apis/page-apis/fetchPersonalPage.ts
  src/components/common-ui/Modal.tsx
  src/components/header/UserActions.tsx
  src/components/modal/page/AddSharedPageModal.tsx
  src/components/modal/page/ModalMenu.tsx
  src/components/modal/page/ModalNotification.tsx
  src/components/page-layout/PageContentSection.tsx
  src/components/page-layout/PageHeaderSection.tsx
  src/components/page-layout/PageLayout.tsx
  src/components/side-bar/SideBar.tsx
  src/hooks/mutations/useCreateSharedPage.ts
  src/hooks/queries/useFetchJoinedPage.ts
  src/hooks/queries/useFetchPersonalPage.ts
  src/layout/layout.tsx
  src/pages/BookmarkPage.tsx
  src/pages/PersonalPage.tsx
  src/pages/SharedPage.tsx
  src/pages/pages/reissue/page.tsx
  src/routes/Router.tsx
  src/stores/.gitkeep
  src/stores/userStore.ts
  src/types/sharedPage.ts
Labels: 📬 API, ✨ Feature, 🎨 HTML&CSS

#79 feat: 랜딩 페이지 이미지 추가 및 리이슈 로직 최적화
  dist/LinkLogo.svg
  dist/assets/LinkManagementImg-R64QW3CI.webp
  dist/assets/ShareImg-CzsgqURw.webp
  dist/assets/landingImage1-B1O07bW-.png
  src/assets/common-ui-assets/landingImage1.png
  src/assets/common-ui-assets/landingImage2.png
  src/assets/common-ui-assets/landingImage3.png
  src/assets/common-ui-assets/landingImage4.png
  src/pages/pages/auth/signup/index.tsx
  src/pages/pages/reissue/page.tsx
Labels: ✨ Feature

#83 refact: 중복된 pages 폴더 구조 정리
  src/pages/auth/login/index.tsx
  src/pages/auth/signup/index.tsx
  src/pages/landing/index.ts
  src/pages/landing/ui/LandingPage.tsx
  src/pages/landing/ui/sections/CtaSection.tsx
  src/pages/landing/ui/sections/FeatureSection.tsx
  src/pages/landing/ui/sections/Footer.tsx
  src/pages/landing/ui/sections/HeroSection.tsx
  src/pages/landing/ui/sections/ProblemSection.tsx
  src/pages/reissue/page.tsx
  src/routes/Router.tsx
Labels: 🔄 Refactor

#84 feat: 소셜 로그인 아이콘 컴포넌트 추가 및 구현
  src/components/common-ui/GithubIcon.tsx
  src/components/common-ui/NaverIcon.tsx
  src/components/common-ui/SocialLoginButton.tsx
  src/pages/auth/login/index.tsx
Labels: ✨ Feature, 🎨 HTML&CSS

#86 feat: 랜딩 페이지 반응형 구현 및 디자인 개선
  src/assets/common-ui-assets/LinkManagementImg.webp
  src/assets/common-ui-assets/YellowCheck.svg
  src/assets/common-ui-assets/landingImage1.png
  src/assets/common-ui-assets/landingImage2.png
  src/assets/common-ui-assets/landingImage3.png
  src/assets/common-ui-assets/landingImage4.png
  src/components/common-ui/button.tsx
  src/pages/landing/ui/sections/CtaSection.tsx
  src/pages/landing/ui/sections/FeatureSection.tsx
  src/pages/landing/ui/sections/Footer.tsx
  src/pages/landing/ui/sections/HeroSection.tsx
  src/pages/landing/ui/sections/ProblemSection.tsx
  src/styles/global.css
Labels: ✨ Feature, 🎨 HTML&CSS

#89 feat: 즐겨찾기, 페이지상세 데이터 분기처리 및 폴더 생성 테스트
  src/apis/favorite-apis/fetchFavorite.ts
  src/apis/folder-apis/createFolder.ts
  src/apis/page-apis/createSharedPage.ts
  src/apis/page-apis/fetchPersonalPage.ts
  src/apis/page-apis/fetchSelectedPage.ts
  src/components/modal/folder/AddFolderModal.tsx
  src/components/page-layout/PageContentSection.tsx
  src/components/page-layout/PageControllerSection.tsx
  src/components/side-bar/SideBar.tsx
  src/hooks/mutations/useCreateFolder.ts
  src/hooks/mutations/useCreateSharedPage.ts
  src/hooks/queries/useFetchFavorite.ts
  src/hooks/queries/useFetchSelectedPage.ts
  src/pages/BookmarkPage.tsx
  src/pages/SharedPage.tsx
  src/routes/Router.tsx
  src/types/folders.ts
  src/types/pages.ts
Labels: 📬 API, ✨ Feature, 🔄 Refactor

#95 feat: 링크 추가 모달 및 생성 기능 구현
  src/apis/link-apis/createLink.ts
  src/components/page-layout-ui/PageControllerSection.tsx
  src/hooks/mutations/useCreateLink.ts
  src/types/links.ts
Labels: 📬 API, ✨ Feature

#96 feat: api 구조에 맞추어 폴더,링크 mapping 및 링크 url 기능 추가
  .github/workflows/deploy.yml
  docker-compose.local.yml
  docker-compose.yml
  src/apis/folder-apis/createFolder.ts
  src/components/modal/folder/AddFolderModal.tsx
  src/components/page-layout-ui/LinkItem.tsx
  src/components/page-layout-ui/PageControllerSection.tsx
  src/components/page-layout-ui/PersonalPageContentSection.tsx
  src/components/page-layout-ui/SharedPageContentSection.tsx
  src/pages/SharedPage.tsx
  src/stores/pageStore.ts
  src/types/folders.ts
  src/types/pageItems.ts
Labels: 📬 API, ✨ Feature

#106 feat: 폴더 crud 구현 및 query key 임시 통일
  src/apis/folder-apis/deleteFolder.ts
  src/apis/folder-apis/fetchFolderDetails.ts
  src/apis/folder-apis/updateFolder.ts
  src/components/common-ui/DropDownInline.tsx
  src/components/common-ui/Modal.tsx
  src/components/modal/folder/AddFolderModal.tsx
  src/components/modal/folder/DeleteFolderModal.tsx
  src/components/page-layout-ui/FolderItem.tsx
  src/components/page-layout-ui/LinkItem.tsx
  src/components/page-layout-ui/ListBookmarkOption.tsx
  src/components/page-layout-ui/PageControllerSection.tsx
  src/components/page-layout-ui/PageHeaderSection.tsx
  src/components/page-layout-ui/PersonalPageContentSection.tsx
  src/components/page-layout-ui/SharedPageContentSection.tsx
  src/hooks/mutations/useCreateFolder.ts
  src/hooks/mutations/useDeleteFolder.ts
  src/hooks/mutations/useUpdateFolder.ts
  src/hooks/queries/useFetchFolderDetails.ts
  src/hooks/useClickOutside.ts
  src/hooks/useDebounce.ts
  src/pages/FolderDetailPage.tsx
  src/pages/PersonalPage.tsx
  src/pages/SharedPage.tsx
  src/routes/Router.tsx
  src/stores/linkActionStore.ts
  src/types/folders.ts
  src/types/pageItems.ts
Labels: 📬 API, ✨ Feature

#109 refact: dropdowninline 관련 로직 리팩토링 및 외부 클릭 감지 훅 분리
  src/components/common-ui/DropDownInline.tsx
  src/components/common-ui/Modal.tsx
  src/components/modal/folder/DeleteFolderModal.tsx
  src/components/modal/folder/FolderTransferModal.tsx
  src/components/modal/link/DeleteLinkModal.tsx
  src/components/page-layout-ui/ListBookmarkOption.tsx
  src/components/page-layout-ui/PageControllerSection.tsx
  src/hooks/useClickOutsideMultiple.ts
Labels: 🔧 BugFix, 🔄 Refactor

#111 feat: 알림 목록 조회 기능 구현 및 타입 정의
  src/apis/alarm-apis/useFetchNotifications.ts
  src/components/header/UserActions.tsx
  src/components/modal/page/ModalNotification.tsx
  src/hooks/queries/useFetchNotification.ts
  src/types/modalAlaram.ts
  src/types/modalAlarm.ts
  vite.config.ts
Labels: 📬 API, ✨ Feature
