Repository LinkrewProject/Linkrew-frontend, pull requests merged in 2025-04, with the labels that each got.

#5 feat: searchbar 추가 및 관련 이미지 추가
  src/shared/assets/Close.svg
  src/shared/assets/Search.svg
  src/shared/ui/SearchBar.tsx
Labels: enhancement

#7 feat: input 추가
  src/shared/assets/Status.svg
  src/shared/ui/Input.tsx
Labels: enhancement

#8 feat: radio 공통 컴포넌트 추가
  src/shared/ui/Radio.tsx
Labels: enhancement

#9 fix: text 색상 수정
  src/shared/ui/Input.tsx
Labels: fix

#12 fix: delete forwardRef in radio component
  src/shared/ui/Radio.tsx
Labels: fix

#13 feat: 컴파운드 컴포넌트 패턴을 사용한 Modal 구현
  src/shared/ui/Modal.tsx
Labels: enhancement

#15 feat: react-hot-toast 설치 및 디자인 커스텀, globalcss 정리
  package-lock.json
  package.json
  src/app/global.css
  src/pages/TEST.tsx
  src/shared/assets/ToastError.svg
  src/shared/assets/ToastSuccess.svg
  src/shared/ui/ToastCustom.tsx
Labels: ✨ Feature, 🧹Setting

#16 fix: 모달 외부 클릭 시 닫힘 로직 수정
  src/shared/ui/Modal.tsx
Labels: 🔄 Refactor

#22 setting: axios instance path, lighthouse
  .lighthouse.json
  src/shared/api/index.ts
Labels: 🧹Setting

#25 Refactor: component style amend
  .prettierrc
  src/pages/TEST.tsx
  src/shared/ui/DropDown.tsx
  src/shared/ui/DropDownInline.tsx
  src/shared/ui/ToggleButton.tsx
  src/shared/ui/ViewToggle.tsx
  src/shared/ui/button.tsx
  src/shared/ui/error-handler/error-handler.ui.tsx
  src/widgets/footer/Footer.tsx
  src/widgets/footer/FooterLanding.tsx
  src/widgets/header/AuthButtons.tsx
  src/widgets/header/UserActions.tsx
  src/widgets/side-bar/SideBar.tsx
Labels: 🔄 Refactor

#27 feat: 레이아웃 설정
  index.html
  package-lock.json
  package.json
  public/LinkLogo.svg
  public/fonts/SpoqaHanSansNeo-Bold.woff2
  public/fonts/SpoqaHanSansNeo-Light.woff2
  public/fonts/SpoqaHanSansNeo-Medium.woff2
  public/fonts/SpoqaHanSansNeo-Regular.woff2
  public/fonts/SpoqaHanSansNeo-Thin.woff2
  public/mockServiceWorker.js
  src/app/layout.tsx
  src/pages/TEST.tsx
  src/widgets/assets/Logo.svg
  src/widgets/header/HamburgerButton.tsx
  src/widgets/header/Header.tsx
  src/widgets/side-bar/SideBar.tsx
Labels: ✨ Feature, 🧹Setting

#29 feat: main page layout markup
  src/app/layout.tsx
  src/app/providers/Router.tsx
  src/pages/TEST.tsx
  src/shared/assets/PageSelectBoxIcon.svg
  src/shared/assets/PageSelectBoxIconCheck.svg
  src/shared/assets/PageSelectBoxIconUp.svg
  src/shared/ui/ViewToggle.tsx
  src/widgets/assets/FolderIcon.svg
  src/widgets/assets/SiteIcon.svg
  src/widgets/header/BreadCrumb.tsx
  src/widgets/header/Header.tsx
  src/widgets/page-layout/PageLayout.tsx
  src/widgets/page-layout/PageSelectBox.tsx
  src/widgets/side-bar/SideBar.tsx
Labels: ✨ Feature, 🔄 Refactor, 🎨 HTML&CSS

#32 fix: 대소문자 구분으로 인한 빌드 에러 해결
  src/pages/auth/login/index.tsx
Labels: 🔧 BugFix

#33 fix: 대소문자 구분으로 인한 빌드 에러 해결 2
  src/pages/auth/signup/index.tsx
Labels: 🔧 BugFix

#30 feat: add landing-page
  package-lock.json
  package.json
  src/app/providers/Router.tsx
  src/pages/landing/index.ts
  src/pages/landing/ui/LandingPage.tsx
  src/pages/landing/ui/sections/CtaSection.tsx
  src/pages/landing/ui/sections/FeatureSection.tsx
  src/pages/landing/ui/sections/Footer.tsx
  src/pages/landing/ui/sections/HeroSection.tsx
  src/pages/landing/ui/sections/ProblemSection.tsx
  src/shared/assets/FolderImg.svg
  src/shared/assets/FooterBg.svg
  src/shared/assets/FooterLogo.svg
  src/shared/assets/LandingMain.svg
  src/shared/assets/LinkManagementImg.svg
  src/shared/assets/ShareImg.svg
  src/shared/assets/YellowCheck.svg
Labels: 🎨 HTML&CSS, 🧹Setting

#31 feat(ui): 체크박스 컴포넌트 개선 및 약관 동의 UI 개선
  src/pages/auth/signup/index.tsx
  src/shared/ui/CheckBox.tsx
Labels: ✨ Feature, 🔄 Refactor, 🎨 HTML&CSS

#34 refact: 로그인 페이지 개선 및 SocialLoginButton 컴포넌트 추출
  src/pages/auth/login/index.tsx
  src/shared/ui/SocialLoginButton.tsx
Labels: 🔄 Refactor

#35 fix(ui): checkbox 컴포넌트의 동적 Tailwind 클래스 문제 해결
  src/shared/ui/CheckBox.tsx
Labels: 🔧 BugFix

#37 refactor: 해상도 변경으로 인한 스타일 값 수정
  src/shared/assets/PlusIcon.svg
  src/shared/assets/ToggleGrid.svg
  src/shared/assets/ToggleList.svg
  src/shared/ui/SearchBar.tsx
  src/shared/ui/ViewToggle.tsx
  src/shared/ui/button.tsx
  src/widgets/assets/Bell.svg
  src/widgets/assets/BookMark.svg
  src/widgets/assets/Hamburger.svg
  src/widgets/assets/Logo.svg
  src/widgets/assets/PersonalPage.svg
  src/widgets/assets/SharedPage.svg
  src/widgets/footer/Footer.tsx
  src/widgets/footer/FooterLanding.tsx
  src/widgets/header/BreadCrumb.tsx
  src/widgets/header/Header.tsx
  src/widgets/page-layout/PageLayout.tsx
  src/widgets/page-layout/PageSelectBox.tsx
  src/widgets/side-bar/SideBar.tsx
Labels: 🔄 Refactor

#38 build: svg 파일 최적화를 통한 빌드 경고 해결 및 번들 크기 감소
  src/shared/assets/BreadCrumbDepth.svg
  src/shared/assets/Close.svg
  src/shared/assets/Consult.svg
  src/shared/assets/Copy.svg
  src/shared/assets/DarkMode.svg
  src/shared/assets/Delete.svg
  src/shared/assets/Deleted.svg
  src/shared/assets/FolderImg.svg
  src/shared/assets/FooterBg.svg
  src/shared/assets/FooterLogo.svg
  src/shared/assets/Google.svg
  src/shared/assets/Kakao.svg
  src/shared/assets/LandingMain.svg
  src/shared/assets/LinkManagementImg.svg
  src/shared/assets/Logo.svg
  src/shared/assets/PageSelectBoxIcon.svg
  src/shared/assets/PageSelectBoxIconCheck.svg
  src/shared/assets/PageSelectBoxIconUp.svg
  src/shared/assets/Search.svg
  src/shared/assets/ShareImg.svg
  src/shared/assets/Status.svg
  src/shared/assets/ToastError.svg
  src/shared/assets/ToastSuccess.svg
  src/shared/assets/ToggleGrid.svg
  src/shared/assets/ToggleList.svg
  src/shared/assets/Transfer.svg
  src/shared/assets/Withdraw.svg
  src/shared/assets/YellowCheck.svg
Labels: 🧹Setting

#41 feat: folder,link 컴포넌트 제작
  src/assets/common-ui-assets/ActiveBookmarkIcon.svg
  src/assets/common-ui-assets/FolderItemIcon.svg
  src/assets/common-ui-assets/InactiveBookmarkIcon.svg
  src/assets/common-ui-assets/PageSortBoxIcon.svg
  src/assets/common-ui-assets/PageSortBoxIconCheck.svg
  src/assets/common-ui-assets/PageSortBoxIconUp.svg
  src/assets/common-ui-assets/ToggleGrid.svg
  src/assets/common-ui-assets/ToggleList.svg
  src/assets/widget-ui-assets/Hamburger.svg
  src/components/common-ui/DirectoryInPage.tsx
  src/components/common-ui/DropDownInline.tsx
  src/components/common-ui/ViewToggle.tsx
  src/components/header/HamburgerButton.tsx
  src/components/header/Header.tsx
  src/components/header/UserActions.tsx
  src/components/page-layout/FolderItem.tsx
  src/components/page-layout/LinkItem.tsx
  src/components/page-layout/ListBookmarkOption.tsx
  src/components/page-layout/PageLayout.tsx
  src/components/page-layout/PageSortBox.tsx
  src/components/side-bar/SideBar.tsx
  src/types/.gitkeep
  src/types/pageItems.ts
Labels: ✨ Feature, 🔄 Refactor, 🎨 HTML&CSS

#43 feat: Grid 모드일때 bookmark 구현 및 해당 상태관리 부모 컴포넌트 변경
  src/assets/common-ui-assets/FolderBookmarkActive.svg
  src/assets/common-ui-assets/FolderBookmarkInactive.svg
  src/assets/common-ui-assets/LinkBookmarkInactive.svg
  src/components/page-layout/FolderItem.tsx
  src/components/page-layout/LinkItem.tsx
  src/components/page-layout/ListBookmarkOption.tsx
  src/components/page-layout/PageLayout.tsx
  src/types/pageItems.ts
Labels: ✨ Feature, 🔄 Refactor, 🎨 HTML&CSS

#44 Optimize/svg assets
  src/assets/common-ui-assets/FolderImg.svg
  src/assets/common-ui-assets/FolderImg.webp
  src/assets/common-ui-assets/FooterBg.svg
  src/assets/common-ui-assets/LandingMain.svg
  src/assets/common-ui-assets/LandingMain.webp
  src/assets/common-ui-assets/ShareImg.svg
  src/assets/common-ui-assets/ShareImg.webp
  src/pages/pages/landing/ui/sections/FeatureSection.tsx
  src/pages/pages/landing/ui/sections/HeroSection.tsx
  src/types/custom.d.ts
  tsconfig.json
  vite.config.ts
Labels: 🎨 HTML&CSS, 🧹Setting

#47 refact: 디자이너님 요청에 따른 컴포넌트 수정 및 dom구조 변경
  build.sh
  src/assets/common-ui-assets/Copy.svg
  src/assets/common-ui-assets/Delete.svg
  src/assets/common-ui-assets/Transfer.svg
  src/components/common-ui/DropDownInline.tsx
  src/components/page-layout/ListBookmarkOption.tsx
  src/components/page-layout/PageSortBox.tsx
Labels: 🔧 BugFix, 🔄 Refactor, 🎨 HTML&CSS

#49 fix: config 중복 내용 수정 및 vercelignore추가
  .vercelignore
  tsconfig.app.json
  tsconfig.json
Labels: 🔧 BugFix

#50 style: 랜딩페이지 수정
  src/assets/common-ui-assets/LinkManagementImg.svg
  src/assets/common-ui-assets/Logo.svg
  src/pages/pages/landing/ui/sections/CtaSection.tsx
  src/pages/pages/landing/ui/sections/FeatureSection.tsx
  src/pages/pages/landing/ui/sections/HeroSection.tsx
  src/pages/pages/landing/ui/sections/ProblemSection.tsx
Labels: 🎨 HTML&CSS

#52 refact: 로그인 페이지 UI 수정
  src/assets/common-ui-assets/Logo.svg
  src/components/common-ui/SocialLoginButton.tsx
  src/pages/pages/auth/login/index.tsx
  src/styles/global.css
Labels: 🔄 Refactor

#53 refact: 회원가입 페이지 UI 수정
  src/components/common-ui/Radio.tsx
  src/pages/pages/auth/signup/index.tsx
Labels: 🔄 Refactor

#56 refact: 랜딩페이지 UI 수정
  src/assets/common-ui-assets/LinkManagementImg.svg
  src/assets/common-ui-assets/LinkManagementImg.webp
  src/pages/pages/landing/ui/sections/HeroSection.tsx
  src/pages/pages/landing/ui/sections/ProblemSection.tsx
Labels: 🔄 Refactor, 🎨 HTML&CSS

#57 feat: modal-notification 제작 및 useClickOutside 커스텀훅 추가
  src/assets/common-ui-assets/AlarmModalClose.svg
  src/assets/common-ui-assets/Profile.webp
  src/components/common-ui/DropDownInline.tsx
  src/components/header/UserActions.tsx
  src/components/modal/modal-alarm/ModalNotification.tsx
  src/components/side-bar/SideBar.tsx
  src/hooks/useClickOutside.ts
  src/types/modalAlaram.ts
Labels: ✨ Feature

#59 Feat/modal menu
  src/components/common-ui/ContextMenu.tsx
  src/components/common-ui/DropDownInline.tsx
  src/components/common-ui/DropDownMenu.tsx
  src/components/header/UserActions.tsx
  src/components/page-layout/PageLayout.tsx
Labels: ✨ Feature

#60 feat: 소셜 로그인 구현 및 HTTPS 설정 추가
  .gitignore
  src/pages/pages/auth/login/index.tsx
  src/pages/pages/reissue/page.tsx
  src/routes/Router.tsx
  vite.config.ts
Labels: ✨ Feature, 🧹Setting
